name: Update DGR Atom Feed

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout your code from main
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
          path: source

      # 2. Set up Python and install dependencies
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        working-directory: source
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 3. Run the scraper, producing source/feeds/dgr.xml
      - name: Run scraper
        working-directory: source
        run: python scraper.py

      # 4. Checkout the gh-pages branch (to commit only the feed)
      - name: Checkout gh-pages
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages

      # 5. Copy the generated feed into the gh-pages checkout
      - name: Copy feed to gh-pages
        run: |
          cp source/feeds/dgr.xml gh-pages/feeds/dgr.xml

      # 6. Commit & push the updated feed
      - name: Commit and Push
        working-directory: gh-pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add feeds/dgr.xml
          git diff --quiet && echo "No changes to commit" || git commit -m "ci: update DGR feed"
          git push origin gh-pages
