name: Update DGR Atom Feed

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout main
      - uses: actions/checkout@v3

      # 2. Setup Python & install deps
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # 3. Run scraper → docs/feeds/dgr.xml
      - run: python scraper.py

      # 4. Commit & push back to main
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/feeds/dgr.xml
          git diff --quiet || git commit -m "ci: update DGR feed"
          git push
